---
name: Testing

env:
  TZ: Asia/Shanghai

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

on:
  push: # If you define neither 'tags' nor 'branches', the workflow will run for either branches or tags.
    branches: [master, main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: [self-hosted, '${{ github.repository }}']
    container:
      image: rockylinux:9
    #services:
    #  nginx:
    #    image: nginx

    steps:
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
      
      - run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/meta | jq .actions
          
        
...
