---
name: Testing

env:
  TZ: Asia/Shanghai

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true

on:
  push: # If you define neither 'tags' nor 'branches', the workflow will run for either branches or tags.
    branches: [master, main]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: [self-hosted, '${{ github.repository }}']
    container:
      image: rockylinux:9

    steps:
      - run: |
          dnf install tar
      # https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - run: |
          cat /etc/os-release
          echo "\$0=$0"
          echo "TZ=$TZ"
          
        
...
